pub mod vowel_count;
pub mod sort_array_by_string_length;
pub mod sum_of_the_first_nth_term_of_series;
pub mod the_highest_profit_wins;
pub mod sort_numbers;
pub mod is_this_a_triangle;
pub mod form_the_minimum;
pub mod two_to_one;
pub mod even_numbers_in_an_array;